deploy: deployFollowSystem deployTweetContract deployPostInteractions

deployFollowSystem:
	npx hardhat run scripts/deployFollowSystem.ts --network localhost

deployTweetContract:
	npx hardhat run scripts/deployTweetContract.ts --network localhost

deployPostInteractions:
	npx hardhat run scripts/deployPostInteractions.ts --network localhost